version: '3'

services:
  adonis-mysql:
    container_name: "${APP_NAME}_MYSQL"
    image: mysql:8
    ports:
      - '3366:3306'
    volumes:
      - $PWD/data:/var/lib/mysql
    restart: 'always'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - adonis-network
  
  phpmyadmin:
    container_name: "${APP_NAME}_PMA"
    image: phpmyadmin/phpmyadmin
    depends_on:
      - adonis-mysql
    environment:
      PMA_HOST: adonis-mysql
    ports:
      - '8585:80'
    restart: 'always'
    volumes: 
      - /phpmyadmin
    networks:
      - adonis-network

  adonis-web:
    container_name: "${APP_NAME}_WEB"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    restart: 'always'
    ports:
      - "3330:3330"
    depends_on:
      - adonis-mysql
    networks:
      - adonis-network

networks: 
  adonis-network:
